<a href="https://colab.research.google.com/github/DSC-University-of-Ghana/intro-to-data-science/blob/main/Copy_of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 




In [ ]:
# To get started, install numpy using pip
!pip install numpy


In [ ]:
# Now to use numpy, import numpy as "np"
import numpy as np

# Numpy Functions

In [ ]:
# "np" object has inherited all the functions from numpy
# Check the directory of numpy

dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_distributor_init',
 '_global

*Let's try out some numpy functions*

In [ ]:
# Function 1: np.arange()
# This works just like the Python "range"
# Create an array of all even numbers from 4 to 20

even_number_list = np.arange(4, 21, 2) 

even_number_list

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
# Functions 2 & 3: np.zeros() and np.ones()
# They return arrays of zeros and ones respectively

# Create an array of 3 ones
ones_array = np.ones(5)

ones_array

array([1., 1., 1., 1., 1.])

In [ ]:
# Create an array of 3 zeros
zeros_array = np.zeros(5)

zeros_array

array([0., 0., 0., 0., 0.])

In [ ]:
# Add "ones_array" to "zeros_array"
ones_array + zeros_array

array([1., 1., 1., 1., 1.])

In [ ]:
# Multiply "ones_array" and "zeros_array"
ones_array * zeros_array

array([0., 0., 0., 0., 0.])

In [ ]:
# Function 4: np.linspace()
# Create a y-axis ranging from -2 to 2 if you have 9 grid markings 

y_axis = np.linspace(-2, 2, 8)

y_axis

array([-2.        , -1.42857143, -0.85714286, -0.28571429,  0.28571429,
        0.85714286,  1.42857143,  2.        ])

In [ ]:
# Function 5: np.eye()
# Create a 2 by 2 array which has ones in its first diagonal and zeros everywhere else
# This is called an identity matrix

identity_matrix = np.eye(3, 3)

identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])


*Also, numpy helps you handle arrays and other generic math functions:*

# Numpy arrays

In [ ]:
# Create a one dimensional array
array_1 = np.array([1, 2, 3, 4, 5])

In [ ]:
# Check for the second element
# Note that numpy arrays work like Python lists

array_1[4] 

5

*Now let's try some attributes and methods of numpy arrays*

In [ ]:
# Attribute 1: Shape
# Check the shape of "array_1"
# The shape shows you the dimensions of the array

array_1.shape

(5,)

In [ ]:
# Define a two-dimensional array 
# Check it's shape

array_2 = np.array([[1, 2],
                    [3, 4],
                    [5, 6]])

array_2.shape

(3, 2)

In [ ]:
# Attribute 2 & 3: array.min() & array.max()
# What is the largest number in array_2

array_2.max()

6

In [ ]:
# What is the smallest number in array_2

array_2.min()

1

*You can also index and select elements in arrays*

In [ ]:
# What is the element in the 2nd row, 1st column of array_2
# You state the row first, followed by the column (i.e array[row][column])

# Note that indexing begins from zero

array_3 = np.array([[2,3], 
                   [4, 7],
                    [9, 5]])
array_3[2][0]

9

*For future reference, you can learn more about np functions, methods and attributes from the documentation*

In [ ]:
# This gives you examples of how to implement that function
# For instance,

np.arange?

In [ ]:
# Pandas

# Awesome Work